#----------------------------------------------------------------------
# This file was generated by C:\Users\zhill\OneDrive\CrashCourse\Part II\alien_invasion\convert_img_to_py.py
#
from wx.lib.embeddedimage import PyEmbeddedImage

get_python_alien = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAADwAAAA6CAIAAABjx604AAAAA3NCSVQICAjb4U/gAAAGaklE'
    b'QVRogc2aT0wTTxTH32JxdwesbJPFyK1JE05K5CIlJIbemsWL5YCJV0z0ZvGIJgY9GerBRJKW'
    b'q2lJrAel4WCEkCjEgwc8qSHhtgluQkMr210ozu8wdbpsu3+74O+bHma3s28+nX3z5s1MGVmW'
    b'IWhJhxLHcAAwGZq8zdwO3D4TCHQe50v10mp51aoC4tEgO1g6X+q8LegcOnWU2ixvGu9EeiJ7'
    b'B3tW9RGPnvY+nWKmOmm0y/eTBVyIVWKUOCEknovP5X5ZO9ZsnlJralpJp45SvtsF3z1dwqVp'
    b'ZZqU40K82F0k5YFfAy4tsCy7c3HHR9Pgr6cLuECJc2KOEkf3o+6N6Lruqb5RfqBnq7OkkBNz'
    b'EiORcnQ/quu6Jzu6rvvzE8/Q0qGkaioAxIU4Jc7jvFdiItMgdinP0D/0HwCAOES9AgBKdf+x'
    b'TDqUvD7iAXoRLwKAWlMBYIgfMn5lE6EdxTHcIl7M47z7R1xB53E+Vo09Vh7TO5OhSc901lqp'
    b'r8woM7FqrIALbuo7QBdwIVaNzSgzpINXcaNHA5ycMcY88OAlhNtBL+PltJImuESvj1+Tgqe3'
    b'aS+hSzB612Z5M1Zx6HJL6Oh+9K5y13RzXV0fF8YB4FH1UWeoTWHApjuqpqaVdAlbDu720FZB'
    b'V9XUdCiNOKRq6sCvgWW83AkuAIRR+HPtc9uvppVpK1dpM407ThNSRFpT10i0Rjy6yl79efTT'
    b'JkmyIcYYV2tVmzptZ3sztMuJLRlJIkDFvaJjzbZCHLqBbnyqfbInJmrlPgHtdSpORVIHcLCh'
    b'bVTUiqdHGGBW9lbcN5QVsxPMBL1sQrdmxi4VRuFRblTDWjqUfnX8qrUC/aoHeny/nIyYoVl4'
    b'A7qAC2kl7c/c2QhxaDu8TcoN6FglRgbW/0qIR0PcEABs1bZUTaWJewgMiZvx1/j2lqB0wo+7'
    b'YUAb2CxvQj8AidMkcQOAEX6EPlPsLubE3BmDUplGHg3YpNCV/ZOlE/VqedU4D0mMlBASZ4ja'
    b'lJF4GS/Td04KjCzLpkhnXPP9K19HHCLZ75a2ZUx+yFqpMRDdezA1xwPfSRrtQyviyhW40sV0'
    b'hcj12LmxWXFWUhwWEWEU/t77vXnd72dpCACIQ3MX5mh+62iEZdmP4Y9jypjcLwNNmC4zl29V'
    b'bpXEEsuyNg+3znw+tgFIjDJm5C/DL23qjwvjb8JvxpSxuBAndxrQZLKRFGkUjb4X39uYiFVi'
    b'xmT6HX7XyjQvzsv9MvnQlqiMMQoACrjw8OCh1c8riaUNdeOmchMA6Eg7kXuQrRbEoaULS5l6'
    b'Zq28ZkMfRuG2KQd5g0bdObpj8v6EkJgKTS0cLQiM0HZgIB7lenOL9UXKYAwPJ6CN+0Yu0Vs1'
    b'0jfy9vxbepnH+ScHT9xnVIhHmd4MAKSraRq4TImeOTU1hRGK/qX2xVPsSwiJGtRMAcsBl0NL'
    b'F5aeHT37pn8zPuWQmhK1HcvJSPLeuXsv6i+80rthvc5ffxB6sHC80JqvuloEEH3FX4nvt4rQ'
    b'Z+oZnuHX1XV/P4AsAqgdq9zamAs5QJOevtR7aff3rn3byUgSA75/7n6mniFb/w2jwJT/lBmG'
    b'4YBjmWYMpTXdLAJSkdQH7UNFrRiHYBto40AEADfcVvLh01SRnggAGBedlgPRZh3QCb1XtRIT'
    b'Gbmb0Pa5UaQn0s10nyq6YxOUuzEjRvej9kNq72Bv9/duQkhc67uGeBQga0JIzIvzcSFOmrCp'
    b'qes62WlhZFnO4/yMMmNvGvFornfOmDBIh5LVfOYoso4yHdi5zDTlfpmRZdmxtmkd0VbSocQC'
    b'K3QJrdtc8Dee6KA7nso5wsj9csjehPvjHEJjc1DUmpO0VbG7WBALs9VZG3e12zXNilmvmafV'
    b'stLTcnOKmdoOb9skyZbQOTHn6BKtkhgpK2ZbTdHTGffaubhjxd0e2l8zRBPMhDG8JISEb1NW'
    b'3G2gjcdW/jTXO0fLUqgjUzsXdxBnjrBd0HKAYprofcgYyDo/6DAdSgGBPo1/NwQ7AZnk/0Df'
    b'XmQPLpC9HqMjkL4wQwfVQxrWAKAGtc5NGR2B9IUZmtztXEH9H6WtGtD/as/Oq8gLbEDT90ju'
    b'BqLhvuFkKBmIKdqn5AU2cg/KGuBrXT7f6YEdlWlsNHr6VF2wc5E+pUHitEJesCJ9OsgOkssm'
    b'dE7MDfcN/xsod6LuEMz/8s5Y/wENS1K7mVVdMQAAAABJRU5ErkJggg==')

